name: Page Monitor

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Write monitoring script from secret
        env:
          SCRIPT_CONTENT: ${{ secrets.MONITOR_SCRIPT }}
        run: |
          echo "$SCRIPT_CONTENT" > /tmp/monitor.sh
          chmod +x /tmp/monitor.sh

      - name: Run monitoring script
        run: /tmp/monitor.sh
